In [12]:
import numpy as np
from collections import defaultdict

In [6]:
a = np.arange(12).reshape((6 ,2))
a.mean(1)

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5])

In [10]:
a = []
a.append(1)
a

[1]

In [65]:
a = np.zeros(10)
a[[2,3]]=1
a

array([0., 0., 1., 1., 0., 0., 0., 0., 0., 0.])

In [24]:
res = defaultdict(lambda:[])
res[1].append(3)
res[0].append(2)
res[0].append(5)

In [64]:
res.pop(1)
res

defaultdict(<function __main__.<lambda>()>, {0: [2, 5]})

In [52]:
list(res.values())

[[3], [2, 5]]

In [39]:
a = np.random.normal(size=[10, 3, 3])
a[2] + a[5], a[3]

(array([[-1.11589844,  1.12306085, -1.16784621],
        [ 0.01073133,  1.04267079,  0.71991043],
        [ 0.11409447,  2.94395916,  0.88281879]]),
 array([[ 0.14083277,  0.56717299, -1.32220649],
        [ 1.35852154,  0.5854947 ,  0.9080086 ],
        [ 0.21412153, -1.36887483, -0.4564365 ]]))

In [46]:
np.array(None).mean(0)

AxisError: axis 0 is out of bounds for array of dimension 0

In [63]:
from copy import copy, deepcopy
class aa:
    def __init__(self, x) -> None:
        self.x=x

a = aa(dict({1:1}))
b = aa(copy(a.x))
b.x[1]=2
a.x

{1: 1}

In [40]:

[a[res[g]].sum(0) for g in range(len(res))]

[array([[-1.11589844,  1.12306085, -1.16784621],
        [ 0.01073133,  1.04267079,  0.71991043],
        [ 0.11409447,  2.94395916,  0.88281879]]),
 array([[ 0.14083277,  0.56717299, -1.32220649],
        [ 1.35852154,  0.5854947 ,  0.9080086 ],
        [ 0.21412153, -1.36887483, -0.4564365 ]])]